const fs = require('fs');
const path = require('path');

const out = path.join(__dirname, '..', 'supabase-config.js');
const url = process.env.SUPABASE_URL || 'https://xozhissdonzcsxqxdido.supabase.co';
const key = process.env.SUPABASE_ANON_KEY || '<YOUR_ANON_PUBLIC_KEY>';

const content = `// Generated by scripts/build-config.js
window.SHERIFF_SUPABASE = { url: '${url}', key: '${key}' };
`;

fs.writeFileSync(out, content, { encoding: 'utf8' });
console.log('Wrote', out);
